[platformio]
default_envs = main

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino

[env:main]
build_src_filter = +<main.cpp>

[env:onboard_blink_test]
build_src_filter = +<onboard_blink_test.cpp>