[platformio]

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps = 
    fastled/FastLED@3.10.3
    mathertel/OneButton@2.6.2
    spacehuhn/SimpleCLI@1.1.4

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_raw = yes