[platformio]
default_envs = main

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
lib_deps = 
    fastled/FastLED
    mathertel/OneButton
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

[env:main]
extends = env
build_src_filter = +<main.cpp>

[env:onboard_blink_test]
extends = env
build_src_filter = +<onboard_blink_test.cpp>

[env:calibration]
extends = env
build_src_filter = +<fastLED_ws2812_calibration.cpp>